// Your 48-day Southeast Asia + Japan + Hawaii trip
import { TripDNA, createTripDNA } from '@/types/trip-dna';
import { Itinerary } from '@/types/itinerary';

export const sampleTripDna: TripDNA = {
  ...createTripDNA(),
  id: 'asia-hawaii-2025',
  travelerProfile: {
    partyType: 'couple',
    travelIdentities: ['food', 'history', 'nature', 'relaxation', 'photography'],
  },
  vibeAndPace: {
    tripPace: 'balanced',
    activitiesPerDay: { min: 2, max: 4 },
    scheduleTolerance: 'some-structure',
    energyPattern: 'morning',
  },
  constraints: {
    dates: {
      type: 'fixed',
      startDate: '2025-02-01',
      endDate: '2025-03-20',
      totalDays: 48,
    },
    budget: {
      currency: 'USD',
      accommodationRange: { min: 80, max: 200, perNight: true },
      dailySpend: { min: 100, max: 250 },
      splurgeMoments: 3,
    },
    accommodation: {
      style: 'boutique',
      priority: 'location',
    },
  },
  interests: {
    destination: 'Thailand → Vietnam → Japan → Hawaii',
    depthPreference: 'depth-fewer',
    food: {
      importance: 'food-focused',
      dietaryRestrictions: [],
      cuisinePreferences: ['thai', 'vietnamese', 'japanese'],
    },
    hobbies: ['photography', 'hiking', 'cooking'],
  },
  logistics: {
    movementTolerance: 'moderate',
    preferredBases: 5,
    transport: {
      comfortable: ['train', 'flight', 'car'],
      avoid: ['bus'],
    },
  },
};

export const sampleItinerary: Itinerary = {
  id: 'asia-hawaii-2025-itinerary',
  tripDnaId: 'asia-hawaii-2025',
  version: 1,
  createdAt: new Date(),
  updatedAt: new Date(),
  meta: {
    title: 'Southeast Asia → Japan → Hawaii Adventure',
    destination: 'Thailand, Vietnam, Japan, Hawaii',
    destinations: ['Thailand', 'Vietnam', 'Japan', 'Hawaii'],
    startDate: '2025-02-01',
    endDate: '2025-03-20',
    totalDays: 48,
    estimatedBudget: {
      currency: 'USD',
      accommodation: 6000,
      food: 3500,
      activities: 2000,
      transport: 2500,
      misc: 1000,
      total: 15000,
      perDay: 312,
    },
  },
  route: {
    bases: [
      {
        id: 'base-1',
        location: 'Bangkok',
        region: 'Thailand',
        nights: 3,
        checkIn: '2025-02-01',
        checkOut: '2025-02-04',
        rationale: 'Gateway city, recover from jet lag, explore temples and street food',
        accommodation: { type: 'boutique', priceRange: '$$', notes: 'Near Khao San or Sukhumvit' },
      },
      {
        id: 'base-2',
        location: 'Chiang Mai',
        region: 'Thailand',
        nights: 5,
        checkIn: '2025-02-04',
        checkOut: '2025-02-09',
        rationale: 'Cultural heart of northern Thailand, temples, cooking classes, day trips',
        accommodation: { type: 'boutique', priceRange: '$$', notes: 'Old City area' },
      },
      {
        id: 'base-3',
        location: 'Phuket/Krabi',
        region: 'Thailand',
        nights: 4,
        checkIn: '2025-02-09',
        checkOut: '2025-02-13',
        rationale: 'Beach relaxation, island hopping, Phi Phi day trip',
        accommodation: { type: 'resort', priceRange: '$$$', notes: 'Beachfront with pool' },
      },
      {
        id: 'base-4',
        location: 'Hanoi',
        region: 'Vietnam',
        nights: 3,
        checkIn: '2025-02-13',
        checkOut: '2025-02-16',
        rationale: 'French colonial charm, Old Quarter, Ha Long Bay access',
        accommodation: { type: 'boutique', priceRange: '$$', notes: 'Old Quarter' },
      },
      {
        id: 'base-5',
        location: 'Hoi An',
        region: 'Vietnam',
        nights: 4,
        checkIn: '2025-02-16',
        checkOut: '2025-02-20',
        rationale: 'Ancient town, lanterns, tailoring, cooking classes, beach nearby',
        accommodation: { type: 'boutique', priceRange: '$$', notes: 'Near Ancient Town' },
      },
      {
        id: 'base-6',
        location: 'Ho Chi Minh City',
        region: 'Vietnam',
        nights: 2,
        checkIn: '2025-02-20',
        checkOut: '2025-02-22',
        rationale: 'Modern Vietnam, War Remnants Museum, Cu Chi Tunnels',
        accommodation: { type: 'hotel', priceRange: '$$', notes: 'District 1' },
      },
      {
        id: 'base-7',
        location: 'Tokyo',
        region: 'Japan',
        nights: 5,
        checkIn: '2025-02-22',
        checkOut: '2025-02-27',
        rationale: 'Modern Japan, neighborhoods, food scene, day trips',
        accommodation: { type: 'hotel', priceRange: '$$$', notes: 'Shibuya or Shinjuku' },
      },
      {
        id: 'base-8',
        location: 'Kyoto',
        region: 'Japan',
        nights: 4,
        checkIn: '2025-02-27',
        checkOut: '2025-03-03',
        rationale: 'Traditional Japan, temples, geisha district, bamboo grove',
        accommodation: { type: 'ryokan', priceRange: '$$$', notes: 'Near Gion' },
      },
      {
        id: 'base-9',
        location: 'Osaka',
        region: 'Japan',
        nights: 2,
        checkIn: '2025-03-03',
        checkOut: '2025-03-05',
        rationale: 'Food capital, Dotonbori, castle, departure city',
        accommodation: { type: 'hotel', priceRange: '$$', notes: 'Near Namba' },
      },
      {
        id: 'base-10',
        location: 'Maui',
        region: 'Hawaii',
        nights: 7,
        checkIn: '2025-03-05',
        checkOut: '2025-03-12',
        rationale: 'Road to Hana, Haleakala, beaches, whale watching season',
        accommodation: { type: 'resort', priceRange: '$$$', notes: 'West Maui or Wailea' },
      },
      {
        id: 'base-11',
        location: 'Oahu',
        region: 'Hawaii',
        nights: 5,
        checkIn: '2025-03-12',
        checkOut: '2025-03-17',
        rationale: 'Waikiki, North Shore, Pearl Harbor, hiking',
        accommodation: { type: 'hotel', priceRange: '$$$', notes: 'Waikiki Beach' },
      },
      {
        id: 'base-12',
        location: 'Big Island',
        region: 'Hawaii',
        nights: 4,
        checkIn: '2025-03-17',
        checkOut: '2025-03-21',
        rationale: 'Volcanoes National Park, black sand beaches, stargazing',
        accommodation: { type: 'resort', priceRange: '$$$', notes: 'Kona side' },
      },
    ],
    movements: [
      { id: 'move-1', from: 'base-1', to: 'base-2', date: '2025-02-04', transportType: 'flight', duration: 75, notes: 'Bangkok → Chiang Mai flight' },
      { id: 'move-2', from: 'base-2', to: 'base-3', date: '2025-02-09', transportType: 'flight', duration: 120, notes: 'Chiang Mai → Phuket flight' },
      { id: 'move-3', from: 'base-3', to: 'base-4', date: '2025-02-13', transportType: 'flight', duration: 150, notes: 'Phuket → Hanoi flight' },
      { id: 'move-4', from: 'base-4', to: 'base-5', date: '2025-02-16', transportType: 'flight', duration: 80, notes: 'Hanoi → Da Nang + car to Hoi An' },
      { id: 'move-5', from: 'base-5', to: 'base-6', date: '2025-02-20', transportType: 'flight', duration: 75, notes: 'Da Nang → HCMC flight' },
      { id: 'move-6', from: 'base-6', to: 'base-7', date: '2025-02-22', transportType: 'flight', duration: 360, notes: 'HCMC → Tokyo flight' },
      { id: 'move-7', from: 'base-7', to: 'base-8', date: '2025-02-27', transportType: 'train', duration: 135, notes: 'Shinkansen Tokyo → Kyoto' },
      { id: 'move-8', from: 'base-8', to: 'base-9', date: '2025-03-03', transportType: 'train', duration: 15, notes: 'Shinkansen Kyoto → Osaka' },
      { id: 'move-9', from: 'base-9', to: 'base-10', date: '2025-03-05', transportType: 'flight', duration: 480, notes: 'Osaka → Maui (via Honolulu)' },
      { id: 'move-10', from: 'base-10', to: 'base-11', date: '2025-03-12', transportType: 'flight', duration: 40, notes: 'Maui → Oahu inter-island' },
      { id: 'move-11', from: 'base-11', to: 'base-12', date: '2025-03-17', transportType: 'flight', duration: 50, notes: 'Oahu → Big Island inter-island' },
    ],
  },
  days: [
    // Day 1 - Bangkok
    {
      id: 'day-1',
      date: '2025-02-01',
      dayNumber: 1,
      baseId: 'base-1',
      theme: 'Arrival & Recovery',
      blocks: [
        {
          id: 'block-1-1',
          type: 'transit',
          startTime: '06:00',
          endTime: '14:00',
          priority: 'must-see',
          isLocked: true,
          notes: 'Arrival, immigration, transfer to hotel',
        },
        {
          id: 'block-1-2',
          type: 'rest-block',
          startTime: '14:00',
          endTime: '17:00',
          priority: 'must-see',
          isLocked: false,
          notes: 'Check in, rest, recover from flight',
        },
        {
          id: 'block-1-3',
          type: 'evening-vibe',
          startTime: '18:00',
          endTime: '21:00',
          activity: {
            id: 'act-1-1',
            name: 'Khao San Road Evening Walk',
            category: 'sightseeing',
            description: 'Explore the famous backpacker street, street food, night market vibe',
            duration: 180,
            bookingRequired: false,
            tags: ['nightlife', 'food', 'walking'],
          },
          priority: 'if-energy',
          isLocked: false,
        },
      ],
    },
    // Day 2 - Bangkok Temples
    {
      id: 'day-2',
      date: '2025-02-02',
      dayNumber: 2,
      baseId: 'base-1',
      theme: 'Temple Day',
      blocks: [
        {
          id: 'block-2-1',
          type: 'morning-anchor',
          startTime: '07:00',
          endTime: '12:00',
          activity: {
            id: 'act-2-1',
            name: 'Grand Palace & Wat Phra Kaew',
            category: 'sightseeing',
            description: 'The most sacred Buddhist temple in Thailand, stunning architecture',
            location: { name: 'Grand Palace', address: 'Na Phra Lan Rd, Phra Borom Maha Ratchawang' },
            duration: 180,
            cost: { amount: 500, currency: 'THB', isEstimate: false },
            bookingRequired: false,
            tips: ['Go early to beat crowds', 'Dress code: cover shoulders and knees', 'Beware of scammers outside'],
            tags: ['temple', 'history', 'must-see'],
          },
          priority: 'must-see',
          isLocked: false,
        },
        {
          id: 'block-2-2',
          type: 'midday-flex',
          startTime: '12:00',
          endTime: '15:00',
          activity: {
            id: 'act-2-2',
            name: 'Wat Pho (Reclining Buddha)',
            category: 'sightseeing',
            description: '46-meter reclining Buddha, traditional Thai massage school',
            location: { name: 'Wat Pho' },
            duration: 90,
            cost: { amount: 200, currency: 'THB', isEstimate: false },
            bookingRequired: false,
            tips: ['Get a Thai massage here - birthplace of Thai massage'],
            tags: ['temple', 'history', 'massage'],
          },
          alternatives: [
            {
              id: 'act-2-2-alt',
              name: 'Wat Arun (Temple of Dawn)',
              category: 'sightseeing',
              description: 'Iconic riverside temple, climb the steep stairs',
              duration: 60,
              bookingRequired: false,
              tags: ['temple', 'photography'],
            },
          ],
          priority: 'must-see',
          isLocked: false,
        },
        {
          id: 'block-2-3',
          type: 'rest-block',
          startTime: '15:00',
          endTime: '17:00',
          priority: 'if-energy',
          isLocked: false,
          notes: 'Return to hotel, pool, rest during heat',
        },
        {
          id: 'block-2-4',
          type: 'evening-vibe',
          startTime: '18:00',
          endTime: '21:00',
          activity: {
            id: 'act-2-3',
            name: 'Chinatown (Yaowarat) Street Food',
            category: 'food',
            description: 'Best street food in Bangkok, seafood, noodles, desserts',
            location: { name: 'Yaowarat Road' },
            duration: 180,
            bookingRequired: false,
            tips: ['T&K Seafood for crab', 'Nai Ek Roll Noodles', 'Go hungry!'],
            tags: ['food', 'street-food', 'must-see'],
          },
          priority: 'must-see',
          isLocked: false,
        },
      ],
    },
    // Day 3 - Bangkok Markets & Modern
    {
      id: 'day-3',
      date: '2025-02-03',
      dayNumber: 3,
      baseId: 'base-1',
      theme: 'Markets & Modern Bangkok',
      blocks: [
        {
          id: 'block-3-1',
          type: 'morning-anchor',
          startTime: '07:00',
          endTime: '11:00',
          activity: {
            id: 'act-3-1',
            name: 'Chatuchak Weekend Market',
            category: 'shopping',
            description: 'One of the largest markets in the world, 15,000+ stalls',
            location: { name: 'Chatuchak Market' },
            duration: 240,
            bookingRequired: false,
            tips: ['Go early before it gets hot', 'Sections 2-4 for clothes', 'Section 26 for art'],
            tags: ['shopping', 'market', 'local'],
          },
          priority: 'must-see',
          isLocked: false,
        },
        {
          id: 'block-3-2',
          type: 'midday-flex',
          startTime: '12:00',
          endTime: '15:00',
          activity: {
            id: 'act-3-2',
            name: 'Jim Thompson House',
            category: 'sightseeing',
            description: 'Beautiful Thai house museum of the American silk entrepreneur',
            location: { name: 'Jim Thompson House' },
            duration: 90,
            cost: { amount: 200, currency: 'THB', isEstimate: false },
            bookingRequired: false,
            tags: ['museum', 'architecture', 'history'],
          },
          priority: 'if-energy',
          isLocked: false,
        },
        {
          id: 'block-3-3',
          type: 'evening-vibe',
          startTime: '18:00',
          endTime: '22:00',
          activity: {
            id: 'act-3-3',
            name: 'Rooftop Bar Sunset',
            category: 'nightlife',
            description: 'Sky Bar or similar rooftop with Bangkok skyline views',
            duration: 180,
            cost: { amount: 1500, currency: 'THB', isEstimate: true },
            bookingRequired: true,
            tips: ['Dress code: smart casual', 'Book ahead for best tables', 'Go for sunset'],
            tags: ['nightlife', 'views', 'splurge'],
          },
          priority: 'if-energy',
          isLocked: false,
        },
      ],
    },
    // Continue with more days...
    // Day 4 - Travel to Chiang Mai
    {
      id: 'day-4',
      date: '2025-02-04',
      dayNumber: 4,
      baseId: 'base-2',
      theme: 'Travel to Chiang Mai',
      blocks: [
        {
          id: 'block-4-1',
          type: 'transit',
          startTime: '08:00',
          endTime: '12:00',
          priority: 'must-see',
          isLocked: true,
          notes: 'Flight Bangkok → Chiang Mai, transfer to hotel',
        },
        {
          id: 'block-4-2',
          type: 'midday-flex',
          startTime: '14:00',
          endTime: '17:00',
          activity: {
            id: 'act-4-1',
            name: 'Old City Walking Tour',
            category: 'sightseeing',
            description: 'Explore the ancient walled city, temples within walking distance',
            duration: 180,
            bookingRequired: false,
            tags: ['walking', 'temples', 'history'],
          },
          priority: 'if-energy',
          isLocked: false,
        },
        {
          id: 'block-4-3',
          type: 'evening-vibe',
          startTime: '18:00',
          endTime: '21:00',
          activity: {
            id: 'act-4-2',
            name: 'Sunday Walking Street Market',
            category: 'shopping',
            description: 'Massive night market with local crafts, food, performances',
            location: { name: 'Ratchadamnoen Road' },
            duration: 180,
            bookingRequired: false,
            tips: ['Only on Sundays', 'Starts at 4pm, best after sunset'],
            tags: ['market', 'food', 'local'],
          },
          priority: 'must-see',
          isLocked: false,
          notes: 'If not Sunday, try Saturday Night Market at Wua Lai Road',
        },
      ],
    },
    // Day 5 - Chiang Mai Temples
    {
      id: 'day-5',
      date: '2025-02-05',
      dayNumber: 5,
      baseId: 'base-2',
      theme: 'Temple Trail',
      blocks: [
        {
          id: 'block-5-1',
          type: 'morning-anchor',
          startTime: '06:00',
          endTime: '11:00',
          activity: {
            id: 'act-5-1',
            name: 'Doi Suthep Temple',
            category: 'sightseeing',
            description: 'Sacred hilltop temple with 309 steps, panoramic city views',
            location: { name: 'Wat Phra That Doi Suthep' },
            duration: 180,
            cost: { amount: 50, currency: 'THB', isEstimate: false },
            bookingRequired: false,
            tips: ['Go at sunrise for best photos', 'Hire a songthaew or Grab', '309 steps or take cable car'],
            tags: ['temple', 'views', 'must-see'],
          },
          priority: 'must-see',
          isLocked: false,
        },
        {
          id: 'block-5-2',
          type: 'midday-flex',
          startTime: '12:00',
          endTime: '15:00',
          activity: {
            id: 'act-5-2',
            name: 'Thai Cooking Class',
            category: 'workshop',
            description: 'Learn to cook authentic Thai dishes, market visit included',
            duration: 180,
            cost: { amount: 1200, currency: 'THB', isEstimate: true },
            bookingRequired: true,
            tips: ['Book Cookery School or similar', 'Morning classes include market tour'],
            tags: ['cooking', 'food', 'local'],
          },
          priority: 'must-see',
          isLocked: false,
        },
        {
          id: 'block-5-3',
          type: 'rest-block',
          startTime: '15:00',
          endTime: '17:00',
          priority: 'if-energy',
          isLocked: false,
        },
        {
          id: 'block-5-4',
          type: 'evening-vibe',
          startTime: '18:00',
          endTime: '21:00',
          activity: {
            id: 'act-5-3',
            name: 'Nimman Road Dining',
            category: 'food',
            description: 'Trendy neighborhood with cafes, restaurants, boutiques',
            location: { name: 'Nimmanhaemin Road' },
            duration: 180,
            bookingRequired: false,
            tags: ['food', 'nightlife', 'trendy'],
          },
          priority: 'if-energy',
          isLocked: false,
        },
      ],
    },
  ],
  foodLayer: [
    // Bangkok
    {
      id: 'food-1',
      type: 'local-classic',
      name: 'Jay Fai',
      cuisine: 'Thai Street Food',
      location: { name: 'Maha Chai Road, Bangkok' },
      priceRange: '$$$',
      reservationRequired: true,
      skipTheHype: false,
      notes: 'Michelin-starred street food, famous crab omelette. Book weeks ahead.',
      mealTime: 'dinner',
    },
    {
      id: 'food-2',
      type: 'local-classic',
      name: 'T&K Seafood',
      cuisine: 'Thai Chinese Seafood',
      location: { name: 'Yaowarat, Chinatown' },
      priceRange: '$$',
      reservationRequired: false,
      skipTheHype: false,
      notes: 'The green-signed place in Chinatown. Get the grilled prawns and crab.',
      mealTime: 'dinner',
    },
    {
      id: 'food-3',
      type: 'casual-backup',
      name: 'Thipsamai Pad Thai',
      cuisine: 'Thai',
      location: { name: 'Maha Chai Road, Bangkok' },
      priceRange: '$',
      reservationRequired: false,
      skipTheHype: true,
      notes: 'Famous pad thai but often overcrowded. Good but not essential.',
      mealTime: 'lunch',
    },
    // Chiang Mai
    {
      id: 'food-4',
      type: 'local-classic',
      name: 'Khao Soi Khun Yai',
      cuisine: 'Northern Thai',
      location: { name: 'Chiang Mai' },
      priceRange: '$',
      reservationRequired: false,
      skipTheHype: false,
      notes: 'Best khao soi in the city. Coconut curry noodles, crispy noodles on top.',
      mealTime: 'lunch',
    },
    {
      id: 'food-5',
      type: 'splurge',
      name: 'David\'s Kitchen',
      cuisine: 'French-Thai Fusion',
      location: { name: 'Chiang Mai' },
      priceRange: '$$$$',
      reservationRequired: true,
      skipTheHype: false,
      notes: 'Intimate fine dining. One of the best in Northern Thailand.',
      mealTime: 'dinner',
    },
    // Vietnam
    {
      id: 'food-6',
      type: 'local-classic',
      name: 'Pho Thin',
      cuisine: 'Vietnamese',
      location: { name: 'Hanoi Old Quarter' },
      priceRange: '$',
      reservationRequired: false,
      skipTheHype: false,
      notes: 'Legendary pho bo since 1979. Simple, perfect beef pho.',
      mealTime: 'breakfast',
    },
    {
      id: 'food-7',
      type: 'local-classic',
      name: 'Bun Cha Huong Lien',
      cuisine: 'Vietnamese',
      location: { name: 'Hanoi' },
      priceRange: '$',
      reservationRequired: false,
      skipTheHype: false,
      notes: 'Obama ate here. Grilled pork with noodles. Worth the hype.',
      mealTime: 'lunch',
    },
    // Japan
    {
      id: 'food-8',
      type: 'local-classic',
      name: 'Tsukiji Outer Market',
      cuisine: 'Japanese Seafood',
      location: { name: 'Tokyo' },
      priceRange: '$$',
      reservationRequired: false,
      skipTheHype: false,
      notes: 'Fresh sushi breakfast, tamago, grilled seafood. Go early.',
      mealTime: 'breakfast',
    },
    {
      id: 'food-9',
      type: 'splurge',
      name: 'Sukiyabashi Jiro (or similar)',
      cuisine: 'Omakase Sushi',
      location: { name: 'Tokyo' },
      priceRange: '$$$$',
      reservationRequired: true,
      skipTheHype: false,
      notes: 'Book months ahead through hotel concierge. Life-changing sushi.',
      mealTime: 'dinner',
    },
  ],
  hobbyLayer: [
    {
      id: 'hobby-1',
      hobby: 'photography',
      activity: {
        id: 'photo-1',
        name: 'Hoi An Lantern Photography Walk',
        category: 'activity',
        description: 'Golden hour and blue hour shooting in the Ancient Town',
        duration: 180,
        bookingRequired: false,
        tags: ['photography', 'sunset'],
      },
      dayId: 'day-16',
      rationale: 'Hoi An is most photogenic at dusk when lanterns light up',
    },
    {
      id: 'hobby-2',
      hobby: 'hiking',
      activity: {
        id: 'hike-1',
        name: 'Haleakala Sunrise Hike',
        category: 'activity',
        description: 'Watch sunrise above the clouds, hike into the crater',
        duration: 360,
        bookingRequired: true,
        tips: ['Reserve sunrise permit in advance', 'Bring warm layers - it\'s cold!'],
        tags: ['hiking', 'nature', 'must-see'],
      },
      dayId: 'day-35',
      rationale: 'Bucket list Hawaiian experience, combines hiking + photography',
    },
  ],
  packingLayer: {
    bagSize: 'medium',
    bagSizeRationale: '48 days across 4 countries with varied climates requires medium bag. Consider carry-on + small checked bag.',
    capsuleWardrobe: [
      { item: 'Quick-dry shirts', quantity: 5, notes: 'Light colors for temples, dark for travel days' },
      { item: 'Lightweight pants/shorts', quantity: 3, notes: 'Zip-off pants work well' },
      { item: 'Light dress/smart casual outfit', quantity: 1, notes: 'For nice dinners in Japan' },
      { item: 'Swimsuit', quantity: 2, notes: 'Thailand beaches + Hawaii' },
      { item: 'Light rain jacket', quantity: 1, notes: 'Packable, works as wind layer' },
      { item: 'Walking shoes', quantity: 1, notes: 'Comfortable for temples and city walking' },
      { item: 'Sandals', quantity: 1, notes: 'Easy on/off for temples' },
      { item: 'Flip flops', quantity: 1, notes: 'Beach and hostel showers' },
    ],
    activitySpecific: [
      { item: 'Temple cover-up sarong', quantity: 1, essential: true, notes: 'For shoulders/knees at temples' },
      { item: 'Day pack', quantity: 1, essential: true, notes: 'For day trips' },
      { item: 'Snorkel gear', quantity: 1, essential: false, notes: 'Optional - can rent in Hawaii' },
      { item: 'Hiking shoes', quantity: 1, essential: true, notes: 'For Haleakala and Japan trails' },
    ],
    electronics: [
      { item: 'Phone + charger', quantity: 1, essential: true },
      { item: 'Camera + lenses', quantity: 1, essential: true, notes: 'Photography hobby' },
      { item: 'Universal adapter', quantity: 2, essential: true, notes: 'Different plugs in each country' },
      { item: 'Portable battery', quantity: 1, essential: true, notes: '20000mAh recommended' },
      { item: 'Kindle/e-reader', quantity: 1, essential: false },
    ],
    toiletries: [
      { item: 'Sunscreen SPF 50', quantity: 2, essential: true, notes: 'Reef-safe for Hawaii' },
      { item: 'Insect repellent', quantity: 1, essential: true, notes: 'DEET for SE Asia' },
      { item: 'Basic toiletries', quantity: 1, essential: true, notes: 'Travel sizes, refill as needed' },
      { item: 'First aid kit', quantity: 1, essential: true, notes: 'Band-aids, Imodium, pain relief' },
    ],
    documents: [
      { item: 'Passport', quantity: 1, essential: true, notes: 'Valid 6+ months, copies stored digitally' },
      { item: 'Visa documents', quantity: 1, essential: true, notes: 'Check Vietnam e-visa requirements' },
      { item: 'Travel insurance docs', quantity: 1, essential: true },
      { item: 'Credit cards', quantity: 2, essential: true, notes: 'Notify bank of travel dates' },
      { item: 'JR Pass', quantity: 1, essential: true, notes: 'Order before Japan leg' },
    ],
    doNotBring: [
      { item: 'Jeans', reason: 'Too heavy and hot for SE Asia, takes forever to dry' },
      { item: 'Laptop', reason: 'Phone is enough for 48 days unless working remotely' },
      { item: 'Too many shoes', reason: 'Sandals + walking shoes + flip flops is enough' },
      { item: 'Bulky towel', reason: 'Hotels provide, quick-dry travel towel if needed' },
      { item: 'Expensive jewelry', reason: 'Risk of loss/theft not worth it' },
    ],
    climateNotes: 'Thailand/Vietnam: Hot and humid (Feb), light breathable fabrics. Japan: Cool (late Feb/early Mar), need layers and light jacket. Hawaii: Warm, trade winds, can be cool at elevation (Haleakala).',
  },
  aiMeta: {
    routeRationale: 'Route optimized to move generally eastward, minimizing backtracking. Thailand first (closest), then Vietnam, then Japan (spring approaching), ending in Hawaii for US re-entry.',
    priorityRanking: [
      { activityId: 'act-2-1', activityName: 'Grand Palace & Wat Phra Kaew', priority: 'must-see', rationale: 'Defining Bangkok experience' },
      { activityId: 'act-5-1', activityName: 'Doi Suthep Temple', priority: 'must-see', rationale: 'Most sacred temple in North Thailand' },
      { activityId: 'act-5-2', activityName: 'Thai Cooking Class', priority: 'must-see', rationale: 'Aligns with food identity' },
    ],
    generatedAt: new Date(),
    modelUsed: 'claude-opus-4-5-20251101',
  },
  userEdits: [],
};

// Function to load sample trip into storage
export async function loadSampleTrip() {
  const { tripDb } = await import('@/lib/db/indexed-db');

  localStorage.setItem(`trip-dna-${sampleTripDna.id}`, JSON.stringify(sampleTripDna));
  localStorage.setItem(`itinerary-${sampleTripDna.id}`, JSON.stringify(sampleItinerary));

  // Save to IndexedDB so it appears on homepage
  await tripDb.save({
    id: sampleTripDna.id,
    tripDna: sampleTripDna,
    itinerary: sampleItinerary,
    createdAt: new Date(),
    updatedAt: new Date(),
    syncedAt: null,
    status: 'generated',
  });

  return sampleTripDna.id;
}
