'use client';

import { Itinerary } from '@/types/itinerary';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import {
  Calendar, MapPin, DollarSign, Package, Utensils,
  Plane, Hotel, Clock, Sparkles
} from 'lucide-react';

interface TripOverviewProps {
  itinerary: Itinerary;
  currentDay?: number;
}

// Helper to format model name for display
function formatModelName(modelId: string): string {
  if (modelId.includes('opus-4-5') || modelId.includes('opus-4.5')) {
    return 'Claude Opus 4.5';
  }
  if (modelId.includes('sonnet')) {
    return 'Claude Sonnet';
  }
  return modelId;
}

export function TripOverview({ itinerary, currentDay = 1 }: TripOverviewProps) {
  const { meta, route, foodLayer, packingLayer, aiMeta } = itinerary;
  const progress = (currentDay / meta.totalDays) * 100;

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="text-center py-6">
        <h1 className="text-3xl font-bold">{meta.title}</h1>
        <p className="text-muted-foreground mt-1">
          {meta.destinations?.join(' → ') || meta.destination}
        </p>
        <div className="flex items-center justify-center gap-4 mt-4 text-sm">
          <span className="flex items-center gap-1">
            <Calendar className="w-4 h-4" />
            {meta.totalDays} days
          </span>
          <span className="flex items-center gap-1">
            <Hotel className="w-4 h-4" />
            {route.bases.length} bases
          </span>
          <span className="flex items-center gap-1">
            <DollarSign className="w-4 h-4" />
            ~${meta.estimatedBudget.total.toLocaleString()}
          </span>
        </div>
        {aiMeta?.modelUsed && !aiMeta.modelUsed.includes('import') && (
          <div className="mt-4">
            <Badge variant="secondary" className="gap-1">
              <Sparkles className="w-3 h-3" />
              Generated by {formatModelName(aiMeta.modelUsed)}
            </Badge>
          </div>
        )}
      </div>

      {/* Progress */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex items-center justify-between mb-2">
            <span className="text-sm font-medium">Trip Progress</span>
            <span className="text-sm text-muted-foreground">
              Day {currentDay} of {meta.totalDays}
            </span>
          </div>
          <Progress value={progress} className="h-2" />
        </CardContent>
      </Card>

      {/* Quick Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatCard
          icon={<MapPin className="w-5 h-5" />}
          label="Bases"
          value={route.bases.length.toString()}
          detail={route.bases.map(b => b.location).join(', ')}
        />
        <StatCard
          icon={<Plane className="w-5 h-5" />}
          label="Moves"
          value={route.movements.length.toString()}
          detail="Hotel changes"
        />
        <StatCard
          icon={<Utensils className="w-5 h-5" />}
          label="Food Spots"
          value={foodLayer.length.toString()}
          detail={`${foodLayer.filter(f => f.type === 'splurge').length} splurges`}
        />
        <StatCard
          icon={<Package className="w-5 h-5" />}
          label="Packing"
          value={packingLayer.bagSize}
          detail={`${packingLayer.capsuleWardrobe.length} wardrobe items`}
        />
      </div>

      {/* Route Overview */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2">
            <MapPin className="w-5 h-5" />
            Route
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {route.bases.map((base, i) => (
              <div key={base.id} className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center text-primary font-medium text-sm">
                  {i + 1}
                </div>
                <div className="flex-1">
                  <div className="font-medium">{base.location}</div>
                  <div className="text-sm text-muted-foreground">
                    {base.nights} nights • {base.checkIn} to {base.checkOut}
                  </div>
                  {base.rationale && (
                    <div className="text-xs text-muted-foreground mt-1 italic">
                      {base.rationale}
                    </div>
                  )}
                </div>
                {i < route.bases.length - 1 && route.movements[i] && (
                  <div className="text-xs text-muted-foreground flex items-center gap-1">
                    <Plane className="w-3 h-3" />
                    {route.movements[i].transportType}
                  </div>
                )}
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Budget Breakdown */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2">
            <DollarSign className="w-5 h-5" />
            Budget Estimate
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            <BudgetRow label="Accommodation" amount={meta.estimatedBudget.accommodation} />
            <BudgetRow label="Food" amount={meta.estimatedBudget.food} />
            <BudgetRow label="Activities" amount={meta.estimatedBudget.activities} />
            <BudgetRow label="Transport" amount={meta.estimatedBudget.transport} />
            <BudgetRow label="Misc" amount={meta.estimatedBudget.misc} />
            <div className="pt-2 border-t flex justify-between font-bold">
              <span>Total</span>
              <span>${meta.estimatedBudget.total.toLocaleString()}</span>
            </div>
            <div className="text-sm text-muted-foreground text-right">
              ~${meta.estimatedBudget.perDay}/day
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function StatCard({
  icon,
  label,
  value,
  detail,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  detail: string;
}) {
  return (
    <Card>
      <CardContent className="pt-4">
        <div className="flex items-center gap-2 text-muted-foreground mb-1">
          {icon}
          <span className="text-sm">{label}</span>
        </div>
        <div className="text-2xl font-bold capitalize">{value}</div>
        <div className="text-xs text-muted-foreground truncate">{detail}</div>
      </CardContent>
    </Card>
  );
}

function BudgetRow({ label, amount }: { label: string; amount: number }) {
  return (
    <div className="flex justify-between text-sm">
      <span className="text-muted-foreground">{label}</span>
      <span>${amount.toLocaleString()}</span>
    </div>
  );
}
